# -*- coding: utf-8 -*-
"""CodeAlpha_Iris_Flower_Classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBawVQcywZ-GLg79Xl5LrnMaXMbd4T-r
"""

!pip install -q kagglehub

import kagglehub

# Download latest version
path = kagglehub.dataset_download("saurabh00007/iriscsv")

print("Path to dataset files:", path)

import os
os.listdir(path)

import pandas as pd

df = pd.read_csv(path + "/Iris.csv")
df.head()

df.info()

df.describe()

df['Species'].value_counts()

# Drop Id column (not useful)
df.drop(columns=['Id'], inplace=True)

# Check missing values
df.isnull().sum()

X = df.drop('Species', axis=1)   # Input features
y = df['Species']                # Output label

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=200)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

train_acc = model.score(X_train, y_train)
test_acc = model.score(X_test, y_test)

print("Train Accuracy:", train_acc)
print("Test Accuracy:", test_acc)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X, y, cv=5)

print("Cross-validation scores:", scores)
print("Mean CV Accuracy:", scores.mean())

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d',
            xticklabels=model.classes_,
            yticklabels=model.classes_)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()



